version: "3.8"

services:
  spa:
    build:
      context: ./newsletter-spa
      dockerfile: DockerFile
    volumes:
      - ./newsletter-spa:/code
    depends_on:
      - api
    ports:
      - 3000:3000
  api:
    build:
      context: ./newsletter-api
      dockerfile: DockerFile
    volumes:
      - ./newsletter-api/app:/code/app
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

volumes:
  db_data:
